# Generated by Django 3.1.4 on 2024-01-23 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['init'], size=None),
            preserve_default=False,
        ),
    ]
