# Generated by Django 3.1.4 on 2024-01-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_link',
            field=models.URLField(max_length=500),
        ),
    ]
