# Generated by Django 3.1.4 on 2024-01-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=25)),
                ('proper_source', models.CharField(max_length=25)),
            ],
        ),
    ]
